# Generated by Django 3.2 on 2022-04-01 16:33

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220401_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='user.png', upload_to='profiles'),
        ),
    ]
